// // CloudHu:604746493@qq.com All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace GlobalGameplayTags
{
	//Factions
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Factions_ID_Alliance);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Factions_ID_Horde);

	//Input
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Sprint);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Roll);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_MeleeAttack);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_HeavyAttack);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Interact);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Throw);

}

namespace InventoryGameplayTags
{
	//Inventory.Item.Quality
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory_Item_Quality_Poor);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory_Item_Quality_Uncommon);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory_Item_Quality_Rare);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory_Item_Quality_Epic);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory_Item_Quality_Legendary);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory_Item_Quality_Mythic);

	//Inventory.Item.Equipment
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory_Item_Type_Sword);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory_Item_Type_Shield);
}


namespace LocomotionTags
{
	//Global Foley
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Handplant);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Jump);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Land);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Run);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_RunStrafe);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_RunBackwds);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Scuff);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_ScuffPivot);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_ScuffWall);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Tumble);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_Walk);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Foley_Event_WalkBackwds);

	//MotionMatching
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Default);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Idle);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Loops);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Pivots);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Starts);
	MYPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MotionMatching_Stops);
	
}
